server {
    listen 80;
    server_name _;

    # Archivos estáticos del frontend
    root /usr/share/nginx/html;
    index index.html;

    resolver 127.0.0.11 valid=30s;
    set $backend http://api:5000;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # ✅ añadido
        proxy_set_header X-Forwarded-Proto $scheme;                    # ✅ añadido

        # Timeouts para tareas largas (útil con Celery)
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_connect_timeout 10s;

        # Necesario para uploads grandes de EEG (tienes 200MB de límite)
        client_max_body_size 210m;
    }

     # Assets con caché agresiva (Vite genera nombres con hash)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2|woff)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Seguridad básica
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
}