services:
  api:
    build: ./backend
    container_name: neuroscreen_api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - eeg_uploads:/app/uploads

  worker:
    build: ./backend
    container_name: neuroscreen_worker
    entrypoint: []
    command: celery -A run.celery worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    volumes:
      - eeg_uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: neuroscreen_frontend
    ports:
      - "80:80"
    depends_on:
      - api

  redis:
    image: redis:7-alpine
    container_name: redis

  db:
    image: postgres:15
    container_name: neuroscreen_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  eeg_uploads: