services:
  api:
    command: flask run --host=0.0.0.0 --no-reload
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app      # hot reload
      - eeg_uploads:/app/uploads
    env_file:
      - .env
      - .env.development

  worker:
    env_file:
      - .env
      - .env.development

  db:
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
      - .env.development

  frontend:
    build:
      args:
        - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env
      - .env.development